Add browser support
sindresorhus/internal-ip pull request #36
Opened 2020-11-17 06:11 UTC by Richienb

Signed-off-by: Richie Bendall <richiebendall@gmail.com>

2020-11-18 13:00 UTC, sindresorhus requested changes

2020-11-18 13:00 UTC, sindresorhus commented on browser.js
> +	peerConnection.createOffer(peerConnection.setLocalDescription.bind(peerConnection), () => { });
```suggestion
	peerConnection.createOffer(peerConnection.setLocalDescription.bind(peerConnection), () => {});
```

2020-11-18 13:00 UTC, sindresorhus commented on browser.js
> +			mediaStream.getTracks().forEach(track => track.stop());
Use for-of loop.

2020-11-18 13:00 UTC, sindresorhus commented on browser.js
> +		return undefined;
You don't need to explicitly use `undefined` here or in the other places.

2020-11-18 13:00 UTC, sindresorhus commented on readme.md
> +The module relies on operating systems tools. On Linux and Android, the `ip` command must be available, which depending on distribution might not be installed by default. It is usually provided by th
This sentence could be confused of saying that `.v6()` works in non-modern browsers.

2020-11-18 13:15 UTC, silverwind commented
Why won't v6 work?

2020-11-19 00:17 UTC, Richienb commented on readme.md
> +The module relies on operating systems tools. On Linux and Android, the `ip` command must be available, which depending on distribution might not be installed by default. It is usually provided by th
This sentence is really difficult to word correctly without adding any ambiguity.

2020-11-19 00:18 UTC, Richienb commented
@silverwind I have only found a way to get the local ipv4 address.

2020-11-19 08:11 UTC, silverwind commented
It seems there is the `candidate attribute` can be more than just IPv4. From [rfc5245](https://tools.ietf.org/html/rfc5245#section-15.1):

> \<connection-address\>:  is taken from RFC 4566 [RFC4566].  It is the
      IP address of the candidate, allowing for IPv4 addresses, IPv6
      addresses, and fully qualified domain names (FQDNs). When parsing
      this field, an agent can differentiate an IPv4 address and an IPv6
      address by presence of a colon in its value - the presence of a
      colon indicates IPv6.  An agent MUST ignore candidate lines that
      include candidates with IP address versions that are not supported
      or recognized.  An IP address SHOULD be used, but an FQDN MAY be
      used in place of an IP address.

So I think some detection for IPv6 based on `:` presence may be good to have. It should ignore FQDNs too.

2020-11-20 01:00 UTC, Richienb commented
It's important that the APIs are consistent. I think the best way to do this is to get the IP, and then either return it or return undefined depending on the type of IP that was requested.

2020-11-20 05:31 UTC, sindresorhus commented
> It's important that the APIs are consistent. I think the best way to do this is to get the IP, and then either return it or return undefined depending on the type of IP that was requested.

👍🏻

2020-11-20 05:45 UTC, Richienb commented
Done!

2020-11-20 09:00 UTC, sindresorhus commented on readme.md
> +The module relies on operating systems tools. On Linux and Android, the `ip` command must be available, which depending on distribution might not be installed by default. It is usually provided by th
```suggestion
The module relies on operating systems tools. On Linux and Android, the `ip` command must be available, which depending on distribution might not be installed by default. It is usually provided by the `iproute2` package. `.v4.sync()` and `.v6.sync()` are not supported in browsers and just return `undefined`.
```

2020-11-20 09:01 UTC, sindresorhus commented on browser.js
> +	} catch { }
```suggestion
	} catch {}
```

Other places too. Please disable Prettier and any other auto-formatters when you work upstream repos.

2020-11-20 09:35 UTC, silverwind commented
> It's important that the APIs are consistent. I think the best way to do this is to get the IP, and then either return it or return undefined depending on the type of IP that was requested.

That'd mean a user will have to call the module twice to get correct results. How about a `internalIp()` root function? Node API could prefer either IPv4 or IPv6 in it.

2020-11-20 09:36 UTC, Richienb commented
@silverwind I think we should start by merging this non-breaking change and then discuss the rest in a future issue.

2020-11-20 10:15 UTC, silverwind commented
Adding a new function is not breaking, but yeah I don't really care that much about this repo and in fact am not even using it currently so, feel free to ignore me :)

2020-11-20 10:50 UTC, Richienb commented
Oh wait I misread, I think the main thing holding us back is the fact that the main function would yield unpredictable results at a slight performance boost.

2020-11-20 15:44 UTC, merged